//
// Created by u on 25.11.21.
//

#ifndef ARTIFICIALLIFE_CONFIGURATION_H
#define ARTIFICIALLIFE_CONFIGURATION_H

constexpr double MUTATION_CHANCE = 0.9;
constexpr double MUTATION_MAGNITUDE_UPTAKE = 1.0/3.0;
constexpr double MUTATION_MAGNITUDE_METABOLISM = 1.0/3.0;
constexpr double MUTATION_MAGNITUDE_SIZE_MUL = 0.4;
constexpr double MUTATION_MAGNITUDE_DIV_TRESHOLD = 40.0;


#endif //ARTIFICIALLIFE_CONFIGURATION_H
